addons:
  apt:
    sources:
    - sourceline: 'deb https://dl.winehq.org/wine-builds/ubuntu/ trusty main'
      key_url: 'https://dl.winehq.org/wine-builds/Release.key'
    packages:
    - winehq-stable
    # - $WINEHQ_VERSION # variables are defined after apt stage!
before_install:
- ls --color /etc/apt
- cat /etc/apt/sources.list
- apt-cache policy wine
script:
- apt-cache policy wine winehq-stable
- wget http://windows.php.net/downloads/releases/php-7.2.0-nts-Win32-VC15-x64.zip
- unzip php*
- wine php.exe
