addons:
  apt:
    sources:
    - sourceline: 'deb https://dl.winehq.org/wine-builds/ubuntu/ trusty main'
      key_url: 'https://dl.winehq.org/wine-builds/Release.key'
    packages:
    - winehq-stable
    # - $WINEHQ_VERSION # variables are defined after apt stage!
before_install:
- ls --color /etc/apt
- cat /etc/apt/sources.list
- apt-cache policy wine winehq-stable
- apt-cache policy wine winehq-stable
- wget http://windows.php.net/downloads/releases/php-7.2.0-nts-Win32-VC15-x64.zip
- unzip php*
- wine php.exe --help
# - wine php.exe -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
- wget https://getcomposer.org/installer --output-document=composer-setup.php
- wine php.exe -r "if (hash_file('SHA384', 'composer-setup.php') === '544e09ee996cdf60ece3804abc52599c22b1f40f4323403c44d44fdfdd586475ca9813a858088ffbc1f233e9b180f061') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;"
# - wine php.exe composer-setup.php
# Some settings on your machine make Composer unable to work properly.
# Make sure that you fix the issues listed below and run this script again:
# The openssl extension is missing, which means that secure HTTPS transfers are impossible.
# If possible you should enable it or recompile php with --with-openssl
- wine php.exe -r "unlink('composer-setup.php');"
- wget https://getcomposer.org/composer.phar
- ls --color
- wine php.exe composer.phar
script:
- true
- wine php.exe -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
