addons:
  apt:
    sources:
    # - ubuntu-toolchain-r-test
    - sourceline: 'https://dl.winehq.org/wine-builds/ubuntu/'
      key_url: 'https://dl.winehq.org/wine-builds/Release.key'
    packages:
    - wine #
    # - gcc-4.9
    # as requested by configure
